django/htmx_lib/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

django/htmx_lib/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('success/', views.success, name='success'),
]

django/htmx_lib/core/models.py
from django.db import models

# Create your models here.

django/htmx_lib/core/forms.py
from django import forms

class FilForm(forms.Form):
    name = forms.CharField()

    def clean_name(self):
        if self.cleaned_data.get('name').startswith("a"):
            raise forms.ValidationError("cannot starts with 'a' ")

django/htmx_lib/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django_htmx.http import push_url, reswap, retarget, trigger_client_event
import random

from .forms import FilForm

def index(request):
    
    if request.htmx:
        print('HTMX')
        form = FilForm(request.GET)
        if form.is_valid():
            #return HttpResponse("successfully submitted form")
            response = HttpResponse("successfully submitted form")
            return trigger_client_event(response, 'film-added')    
        context = {'form': form}
        response = render(request, 'form.html', context)
        return retarget(response, '#page-content')
    else:
        print('no HTMX')
        context = {'form': FilForm()}
        return render(request, 'index.html', context)

def success(request):
    if random.random() < 0.35:
        print("pooling terminating ...")
        return HttpResponseStopPolling()
    
    return HttpResponse("congratulações - sucesso")

django/htmx_lib/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://unpkg.com/htmx.org@1.9.6" integrity="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni" crossorigin="anonymous"></script>
</head>
<body hx-on="film-added: document.body.style.backgroundColor='#aaa';">
    <div class="container mt-4" style="margin: 25px;">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

django/htmx_lib/core/templates/form.html
<form   id="submit-form"
        hx-get="{% url 'core:index' %}"
        hx-target="body">
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

django/htmx_lib/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>

<a  id="htmx-link" 
    href="{% url 'core:index' %}" 
    hx-boost="true" 
    hx-target="#htmx-content">new page</a>

<ul id="htmx-content"></ul>

<div id="page-content">
    {% include 'form.html' %}
</div>

<!-- <div hx-trigger="every 2s" 
     hx-target="#htmx-content"
     hx-get="{% url 'core:success' %}"
     hx-swap="beforeend">
</div> -->

{% endblock %}

django/htmx_lib/core/templates/partial.html
<li>{% lorem %}</li>